name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.1.4
  - pytest=6.2.2
  #- openblas=0.3.21
  #- scipy=1.5.2 #causes problems 
  - pip=20.3.3
  - pip:
      - wandb==0.10.21
